### ISSUE TITLE
Auto indent not indenting anything

### ISSUE THREAD

**Issue by willobar** [jugglingnutcase/language-powershell#32]
I have Auto Indent and Auto Indent On Paste both checked in the package settings. When I try to paste pre-indented content, it is always pasted left aligned. It appears to be stripping out all indents on paste instead of auto indenting.

**Comment by jugglingnutcase** [comment]
Thanks for the report :smile:, i'll take a look.

**Comment by jugglingnutcase** [comment]
OK, i don't think i've got the best solution for this pinned down, but i've got something. Look for an update for this.

If you have any future problems, i've created a folder in this project (in "spec/fixtures/indents") for examples of how PS files should be indented that are used in this project's tests. If you find any other problems, it would be helpful to me to have an example of what doesn't work PR'd into that folder.

Thanks for letting me know about this :smile:, i hope this helps. If everything goes bad, you can also try the option that preserves the original indentation from the paste.
