### ISSUE TITLE
Here-string delimiter is not identified as such

### ISSUE THREAD

**Issue by mlalkaka** [jugglingnutcase/language-powershell#49]
Here-strings -- strings that begin with `@"` and end with `"@` on another line -- are not correctly identified. As a result, any code below a here-string is colored as if it was a string.

In the following example, everything after `"@` is being highlighted as a string in Atom with the language-powershell package.
```powershell
function Foo
{
    $SomeLongString = @"
    This is a here-string in PowerShell.
    "@
}

function Bar
{
    Write-Host "Bar"
}
```

Any chance this could get fixed? I'm loving the package, so thanks for making it!

**Comment by vors** [comment]
Duplicate of https://github.com/jugglingnutcase/language-powershell/issues/43
It's by design in the language: `"@` has to be at the beginning of the line to be treated as closure.

**Comment by mlalkaka** [comment]
Thanks! I just figured that out too. Sorry about the noise; I'll close this issue now.

**Comment by vors** [comment]
No worries, apparently it's a common problem. I have seen it reported twice here and at least once on https://github.com/SublimeText/PowerShell

**Comment by jugglingnutcase** [comment]
Thanks @vors!
