### ISSUE TITLE
Not loading profile file because of script execution policy

### ISSUE THREAD

**Issue by Sako73** [jugglingnutcase/language-powershell#54]
I try to run Powershell scripts, and I get the following error:

File C:\Users\<user>\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this system.

In a Powershell shell, I have confirmed that the policy is "Unrestricted" for both the user and the administrator.  I have also run the script file as the user and administrator in a Powershell console.

I have tried this as my regular user, and running Atom as administrator.

It is a Windows 10 system.

Thanks.

**Comment by jugglingnutcase** [comment]
Hi! Thanks for reaching out 😄 

i don't believe this is the right place to report this issue. This package provides PowerShell syntax highlighting and some snippets to the Atom editor, it isn't responsible for running scripts or loading profiles or anything like that. I'm afraid you'll have to find answers for this elsewhere! [Maybe this stackoverflow post is a good place to start?](http://stackoverflow.com/questions/4037939/powershell-says-execution-of-scripts-is-disabled-on-this-system)
